update Makefile.base

diff --git a/Makefile.base b/Makefile.base
--- a/Makefile.base
+++ b/Makefile.base
@@ -2,10 +2,12 @@
 # 
 # Version:
 # - 1.0.0: add a version comment
-# - 1.1.0: add help, sjar
-# - 1.1.1: fix "jar" instead of ${JAR}
+# - 1.1.0: add 'help', 'sjar'
+# - 1.2.0: add 'apk'
+# - 1.2.1: improve 'apk' and add 'android'
+# - 1.3.0: add 'man' for man(ual) pages
 
-# Required parameters (the commented out ones are supposed to change per project):
+# Required parameters (the commented out ones are supposed to be per project):
 
 #MAIN = path to main java source to compile
 #MORE = path to supplementary needed resources not linked from MAIN
@@ -13,8 +15,12 @@
 #PREFIX = usually /usr/local (where to install the program)
 #TEST = path to main test source to compile
 #JAR_FLAGS += a list of things to pack, each usually prefixed with "-C bin/"
-#SJAR_FLAGS += a list of things to pack, each usually prefixed with "-C src/", for *-sources.jar files
+#SJAR_FLAGS += a list of things to pack, each usually prefixed with "-C src/",
+#		for *-sources.jar files
 #TEST_PARAMS = any parameter to pass to the test runnable when "test-run"
+#ID_FOR_ANDROID = id of activity to launch for Android
+#RM_FOR_ANDROID = packages (if it ends with /) or classes to ignore for APK 
+#		generation
 
 JAVAC = javac
 JAVAC_FLAGS += -encoding UTF-8 -d ./bin/ -cp ./src/
@@ -24,12 +30,12 @@ JAR = jar
 RJAR = java
 RJAR_FLAGS += -jar
 
-all: build jar
+all: build jar man
 
 help:
 	@echo "Usual options:"
 	@echo "=============="
-	@echo "	make		: to build the jar file"
+	@echo "	make		: to build the jar file and man pages IF possible"
 	@echo "	make help	: to get this help screen"
 	@echo "	make libs	: to update the libraries into src/"
 	@echo "	make build	: to update the binaries (not the jar)"
@@ -41,9 +47,13 @@ help:
 	@echo "	make run	: to run the program from the binaries"
 	@echo "	make run-test	: to run the test program from the binaries"
 	@echo "	make jrun	: to run the program from the jar file"
-	@echo "	make install	: to install the application into $PREFIX"
+	@echo "	make install	: to install the application into $$PREFIX"
+	@echo "	make android	: to prepare the sources in android/ for Studio"
+	@echo "	make apk	: to compile the APK file"
+	@echo " make ifman	: to make the manual pages (if pandoc is found)"
+	@echo " make man	: to make the manual pages (requires pandoc)"
 
-.PHONY: all clean mrproper mrpropre build run jrun jar sjar resources test-resources install libs love 
+.PHONY: all clean mrproper mrpropre build run jrun jar sjar resources test-resources install libs love apk android ifman man
 
 bin:
 	@mkdir -p bin
@@ -73,14 +83,16 @@ test: test-resources
 
 clean:
 	rm -rf bin/
+	rm -rf android/.gradle android/build android/app/build android/app/build.gradle
+	[ ! -L android/app/src/main/java ] || rm -rf android/app/src
 	@echo Removing sources taken from libs...
 	@for lib in libs/*-sources.jar libs/*-sources.patch.jar; do \
 		if [ "$$lib" != 'libs/*-sources.jar' -a "$$lib" != 'libs/*-sources.patch.jar' ]; then \
 			basename "$$lib"; \
-			${JAR} tf "$$lib" | while read -r ln; do \
+			jar tf "$$lib" | while read -r ln; do \
 				[ -f "src/$$ln" ] && rm "src/$$ln"; \
 			done; \
-			${JAR} tf "$$lib" | tac | while read -r ln; do \
+			jar tf "$$lib" | tac | while read -r ln; do \
 				[ -d "src/$$ln" ] && rmdir "src/$$ln" 2>/dev/null || true; \
 			done; \
 		fi \
@@ -91,8 +103,12 @@ mrproper: mrpropre
 mrpropre: clean
 	rm -f $(NAME).jar
 	rm -f $(NAME)-sources.jar
+	rm -f $(NAME).apk
+	rm -f $(NAME)-debug.apk
 	[ ! -e VERSION ] || rm -f "$(NAME)-`cat VERSION`.jar"
 	[ ! -e VERSION ] || rm -f "$(NAME)-`cat VERSION`-sources.jar"
+	[ ! -e VERSION ] || rm -f "$(NAME)-`cat VERSION`.apk"
+	[ ! -e VERSION ] || rm -f "$(NAME)-`cat VERSION`-debug.apk"
 
 love:
 	@echo "	...not war."
@@ -123,7 +139,7 @@ libs: bin
 	@[ -e bin/libs -o ! -d libs ] || (cd src && for lib in ../libs/*-sources.jar ../libs/*-sources.patch.jar; do \
 		if [ "$$lib" != '../libs/*-sources.jar' -a "$$lib" != '../libs/*-sources.patch.jar' ]; then \
 			basename "$$lib"; \
-			${JAR} xf "$$lib"; \
+			jar xf "$$lib"; \
 		fi \
 	done )
 	@[ ! -d libs ] || touch bin/libs
@@ -172,4 +188,104 @@ install:
 	echo "#!/bin/sh" > "$(PREFIX)/bin/$(NAME)"
 	echo "$(RJAR) $(RJAR_FLAGS) \"$(PREFIX)/lib/$(NAME).jar\" \"\$$@\"" >> "$(PREFIX)/bin/$(NAME)"
 	chmod a+rx "$(PREFIX)/bin/$(NAME)"
+	if [ -e "man/man1/$(NAME).1" ]; then \
+		cp -r man/ "$(PREFIX)"/share/; \
+	fi
+
+android: android/app/src
+
+android/app/src:
+	@[ -d android ] || echo No android/ directory found
+	@[ -d android ]
+	@[ -e android/local.properties ] || echo 'You need to create android/local.properties and add "sdk.dir=PATH_TO_SDK"'
+	@[ -e android/local.properties ]
+	@mkdir -p android/app/src/main
+	@echo Linking sources...
+	@( \
+		cd android/app/src/main; \
+		ln -s ../../../../src/AndroidManifest.xml .; \
+		ln -s ../../../../res .; \
+		ln -s ../../../../src ./java; \
+	)
+	@echo Fixing configuration...
+	@( \
+		cd android/app/src/main/java; \
+		excl="\\n";\
+		if [ "${RM_FOR_ANDROID}" != "" ]; then \
+			echo Ignoring uneeded sources...; \
+			for file in ${RM_FOR_ANDROID}; do \
+				excl="$${excl}exclude '**/$${file}'\\n";\
+			done; \
+		fi; \
+		cd ../../../ ; \
+		cat build.gradle.base \
+			| sed 's:\(applicationId "\)":\1${ID_FOR_ANDROID}":' \
+			| sed "s:\s*exclude '':$$excl:g" \
+		> build.gradle; \
+	)
+
+apk: libs ${NAME}.apk
+	@echo Building APK files...
+
+${NAME}.apk: ${NAME}-debug.apk
+
+${NAME}-debug.apk: android
+	@echo Starting gradlew assemble...
+	@( \
+		cd android/; \
+		bash gradlew assemble && ( \
+			cd ..; \
+			cp android/app/build/outputs/apk/release/app-release-unsigned.apk ${NAME}.apk; \
+			cp android/app/build/outputs/apk/debug/app-debug.apk ${NAME}-debug.apk; \
+			[ ! -e VERSION ] || echo Copying to "$(NAME)-`cat VERSION`.apk"...; \
+			[ ! -e VERSION ] || cp $(NAME).apk "$(NAME)-`cat VERSION`.apk"; \
+			[ ! -e VERSION ] || echo Copying to "$(NAME)-`cat VERSION`-debug.apk"...; \
+			[ ! -e VERSION ] || cp $(NAME).apk "$(NAME)-`cat VERSION`-debug.apk"; \
+		); \
+	)
+
+ifman:
+	@if pandoc -v >/dev/null 2>&1; then \
+		make man; \
+	else \
+		echo "man pages not generated: "'`'"pandoc' required"; \
+	fi
+
+man: 
+	@echo Checking for possible manual pages...
+	@if [ -e README.md ]; then \
+		echo Sources found for man pages; \
+		if pandoc -v >/dev/null 2>&1; then \
+			ls README*.md 2>/dev/null \
+					| grep 'README\(-..\|\)\.md' \
+					| while read man; do \
+				echo "	Processing page $$lang..."; \
+				lang="`echo "$$man" \
+					| sed 's:README\.md:en:' \
+					| sed 's:README-\(.*\)\.md:\1:'`"; \
+				mkdir -p man/"$$lang"/man1; \
+				( \
+					echo ".TH \"${NAME}\" 1 `\
+						date +%Y-%m-%d\
+						` \"version `cat VERSION`\""; \
+					echo; \
+					UNAME="`echo "${NAME}" \
+						| sed 's:\(.*\):\U\1:g'`"; \
+					( \
+						cat "$$man" | head -n1 \
+	| sed 's:.*(README\(-fr\|\)\.md).*::g'; \
+						cat "$$man" | tail -n+2; \
+					) | sed 's:^#\(#.*\):\1:g' \
+	| sed 's:^\(#.*\):\U\1:g;s:# *'"$$UNAME"':# NAME\n'"${NAME}"' \\- :g' \
+	| sed 's:--:——:g' \
+	| pandoc -f markdown -t man | sed 's:——:--:g' ; \
+				) > man/"$$lang"/man1/"${NAME}.1"; \
+			done; \
+			mkdir -p "man/man1"; \
+			cp man/en/man1/"${NAME}".1 man/man1/; \
+		else \
+			echo "man pages generation: pandoc required" >&2; \
+			false; \
+		fi; \
+	fi;
 
